#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔥 Running pre-push checks..."

# Run npm install
echo "📦 Installing dependencies..."
npm i
INSTALL_EXIT_CODE=$?

if [ $INSTALL_EXIT_CODE -ne 0 ]; then
  echo ""
  echo "❌❌❌ NPM INSTALL FAILED WITH CODE $INSTALL_EXIT_CODE ❌❌❌"
  echo "❌❌❌ PUSH ABORTED ❌❌❌"
  echo ""
  # Force exit with unmistakable error
  exec < /dev/null
  exit 128
fi

# Run build script
echo "🛠️ Building project..."
npm run build
BUILD_EXIT_CODE=$?

if [ $BUILD_EXIT_CODE -ne 0 ]; then
  echo ""
  echo "❌❌❌ BUILD FAILED WITH CODE $BUILD_EXIT_CODE ❌❌❌"
  echo "❌❌❌ PUSH ABORTED ❌❌❌"
  echo ""
  # Force exit with unmistakable error
  exec < /dev/null
  exit 128
fi
git add .
echo "✅ All checks passed! Pushing to remote..."